name: Flatpak lint

on:
  workflow_dispatch:

jobs:
  lint:
    name: flatpak-builder-lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install flatpak
        run: sudo apt-get update -y && sudo apt-get install -y flatpak

      - name: Add Flathub remote
        run: flatpak --user remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

      - name: Install org.flatpak.Builder
        run: flatpak --user install -y flathub org.flatpak.Builder

      - name: Lint manifest
        run: |
          flatpak run --command=flatpak-builder-lint org.flatpak.Builder \
            manifest build-aux/io.github.todevelopers.GseProfiler.yml

      - name: Install flatpak-builder and GNOME runtime
        run: |
          sudo apt-get install -y flatpak-builder
          flatpak --user install -y flathub org.gnome.Platform//50 org.gnome.Sdk//50

      - name: Build repo for lint
        run: |
          flatpak-builder \
            --disable-rofiles-fuse \
            --force-clean \
            --repo=repo \
            flatpak_app \
            build-aux/io.github.todevelopers.GseProfiler.yml

      - name: Lint repo
        run: flatpak run --command=flatpak-builder-lint org.flatpak.Builder repo repo
